# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # quand le conteneur va faire un new MySlugger($sluggerInterface, true ou false)
    # il saura quoi transmettre comme second argument
    # cela lui donne "un comportement par défaut"
    App\Service\MySlugger:
        arguments:
            $toLower: true 
       # écouteur entité doctrine (Doctrine EntityListener)
    App\EventListener\MovieSlug:
        tags:
            # pour prePersist
            -
                # nom du type d'écouteur
                name: 'doctrine.orm.entity_listener'
                # type d'événement à écouter
                event: 'prePersist'
                # quelle entité écouter
                entity: 'App\Entity\Movie'
                # méthode du Listener à appeler
                method: 'slugify'
            # pour preUpdate, on duplique le bloc...
            -
                # nom du type d'écouteur
                name: 'doctrine.orm.entity_listener'
                # type d'événement à écouter
                event: 'preUpdate'
                # quelle entité écouter
                entity: 'App\Entity\Movie'
                # méthode du Listener à appeler
                method: 'slugify'
